server {
    listen 3001;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /ui/console/assets/environment.json {
        return 404;
    }

    location /ui/console/ {
        try_files $uri $uri/ /ui/console/index.html;
    }

    location = /ui/console {
        return 308 /ui/console/;
    }
}
